name: Populate Puzzles in DB

on:
  workflow_dispatch:

jobs:
  populate-puzzles:
    runs-on: ubuntu-latest
    steps:
      - name: Download Lichess puzzle dataset
        run: |
          wget https://database.lichess.org/lichess_db_puzzle.csv.zst
          zstd -d lichess_db_puzzle.csv.zst
          ls -la
